spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springCloud_Sell?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
