evn: 
  dev3
# 测试 
girl:
  name: lili
  age: 18


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8881
spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/springCloud_Sell?useUnicode=true&characterEncoding=UTF-8
  jpa:
      show-sql: true
